### ISSUE TITLE
Forum width should be 100%.

### ISSUE THREAD

**Issue by physics515** [physics515/hiveFive.life#5]
Forum should stretch to 100% width even on very large screens.
![capture](https://user-images.githubusercontent.com/7359379/32477459-02662c02-c344-11e7-9751-77b3ff659345.PNG)

**Comment by sick115** [comment]
Should be fixed. Need someone with access to a pc to test that for me though.

**Comment by physics515** [comment]
Not yet fixed on desktop. I'll upload a photo with what it looks like when I get off work.

**Comment by physics515** [comment]
I may need to figure this one out since I have access to a deaktop.

**Comment by physics515** [comment]
fixed.

![capture](https://user-images.githubusercontent.com/7359379/33868738-5c7c0b2a-deca-11e7-85da-4666deafaecf.PNG)
